.PHONY: all

run:
	@echo "Running AWK script proj2: "
	awk -f ./awk/code.awk ../data/data.csv > ./output/proj2.csv
	@echo "new feature proj2:"
	awk -f ./awk/newf.awk ../data/data.csv > ./output/newf.csv
